### ISSUE TITLE
filter incoming requests

### ISSUE THREAD

**Issue by MindHunter86** [MindHunter86/anilibria-hlp-service#11]
```
vscode ➜ /workspaces/repos/anilibria-hlp-service (feature/anilibria) $ go run --race main.go -l trace --http-debug
12:45PM DBG ready... func=main.main.func2
12:45PM DBG args=["/tmp/go-build1613621553/b001/exe/main","-l","trace","--http-debug"] func=main.main.func2
12:45PM DBG initiate main event loop func=app.(*App).loop
12:45PM DBG called fake quality func=app.(*App).getUriWithFakeQuality
panic: runtime error: index out of range [6] with length 2

goroutine 71 [running]:
github.com/MindHunter86/anilibria-hlp-service/app.(*TitleSerieRequest).getTitleQuality(...)
	/workspaces/repos/anilibria-hlp-service/app/methods.go:246
github.com/MindHunter86/anilibria-hlp-service/app.(*App).getUriWithFakeQuality(0xc0002b9778?, {0xc00034e0f7, 0x9}, 0x3)
	/workspaces/repos/anilibria-hlp-service/app/app.go:253 +0xec5
github.com/MindHunter86/anilibria-hlp-service/app.(*App).hlpHandler(0x63aae8ed?, 0xc0005f4000)
	/workspaces/repos/anilibria-hlp-service/app/app.go:223 +0x895
github.com/valyala/fasthttp.(*Server).serveConn(0xc0005ea000, {0xdb6208?, 0xc0000b0018})
	/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/server.go:2338 +0x1c03
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0005ec000, 0xc0000ce020)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/workerpool.go:224 +0xef
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/workerpool.go:196 +0x54
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/workerpool.go:195 +0x365
exit status 2

```

**Comment by MindHunter86** [comment]
`curl -ISsL -H "X-Client-URI: /huy.m3u8" -H "X-Client-ID: ExoPlayer" -H "X-Cache-Server: cache6.libria.fun" -H "X-Forwarded-For: 77.222.114.203" http://127.0.0.1:8089/huy.m3u8`
